export * from './NavBar/NavBar'
export * from './Banner/Banner'
export * from './Newsletter/Newsletter'
export * from './Contact/Contact'
export * from './Footer/Footer'
export * from './Skills/Skills'